### PR TITLE
Fix the bug that event raises exceptions

### PR DESCRIPTION
**Pull request by taoyouh**
- RoutedEventArgs instances are now constructed with dispatcher to avoid thread faults. (Issue #60)
- Some async void functions are renamed from "xxxAsync" to "xxx" because async void functions are not awaitable and does not appear async to caller, making the "xxxAsync" name confusing.

### CODE REVIEW

**Comment by JunielKatarn** [comment]
Does this fix seem related to this issue too? #65.

**Comment by taoyouh** [comment]
@JunielKatarn This PR fixes similar error, but I am not sure whether your issue can be fixed by this. You can clone my repository and make some tests.

**Comment by vbfnet** [comment]
I am getting the same error in UWP app when using this package. The "Media Opened", "Media Failed" etc. events are failing because of thread faults. 

I believe the changes made taoyouh will fix the threading issues. Is there a way to get the nuget package with the changes included by taoyouh?

Thanks

**Comment by taoyouh** [comment]
@vbfnet I think the only way to get the nuget package with my changes is that somebody create a new package based on my repository.

**Comment by vbfnet** [comment]
@taoyouh Thanks for clarifying.

**Comment by kakone** [comment]
Resolved by 211399e92fe2533a0081cd72601affd6b09c61cb

**Comment by vbfnet** [comment]
Excellent ! Thanks and will test asap

**Comment by kakone** [comment]
You can test it with the new [NuGet package 3.1.0](https://www.nuget.org/packages/VLC.MediaElement/3.1.0)

**Comment by vbfnet** [comment]
Yes, No more threading errors for The "Media Opened", "Media Failed" etc.
 
Great job!

**Pull request closed without merging**
